!at.ac.tuwien.dsg.depictool.entity.ElasticDataObject
listOfDataElasticityMetrics: 
- !at.ac.tuwien.dsg.depictool.entity.DataElasticityMetric
   name: data completeness
   listOfRanges: 
   - !at.ac.tuwien.dsg.depictool.entity.Range
      rangeID: r1
      toValue: 75.0
   - !at.ac.tuwien.dsg.depictool.entity.Range
      fromValue: 76.0
      rangeID: r2
      toValue: 90.0
   - !at.ac.tuwien.dsg.depictool.entity.Range
      fromValue: 91.0
      rangeID: r3
      toValue: 100.0
   unit: '%'
- !at.ac.tuwien.dsg.depictool.entity.DataElasticityMetric
   name: throughput
   listOfRanges: 
   - !at.ac.tuwien.dsg.depictool.entity.Range
      rangeID: t1
      toValue: 0.1
   - !at.ac.tuwien.dsg.depictool.entity.Range
      fromValue: 0.11
      rangeID: t2
      toValue: 0.29
   - !at.ac.tuwien.dsg.depictool.entity.Range
      fromValue: 0.3
      rangeID: t3
      toValue: 1.0
   unit: Mbps
listOfDataObjectFunctions: 
- !at.ac.tuwien.dsg.depictool.entity.DataObjectFunction
   name: pc-100
   numberOfDataItems: 100
   query: Select * from PowerConsumption Where Time = Today
- !at.ac.tuwien.dsg.depictool.entity.DataObjectFunction
   name: pc-200
   numberOfDataItems: 200
   query: Select * from PowerConsumption Where Time = Today
listOfElasticStates: 
- !at.ac.tuwien.dsg.depictool.entity.ElasticState
   eStateID: eState1
   listOfMetricRanges: 
   - r1
   - t1
   price: 0.05
- !at.ac.tuwien.dsg.depictool.entity.ElasticState
   eStateID: eState2
   listOfMetricRanges: 
   - r3
   - t2
   price: 0.08
