!at.ac.tuwien.dsg.depictool.entity.DataElasticityProcessConfiguration
listOfMetricElasticityProcesses: 
- !at.ac.tuwien.dsg.depictool.entity.MetricElasticityProcess
   listOfControlActions: 
   - !at.ac.tuwien.dsg.depictool.entity.ControlAction
      actionID: LSR
      listOfParameters: 
      - !at.ac.tuwien.dsg.depictool.entity.Parameter
         paraName: expectedDataCompleteness
         type: double
         value: 100
      triggerValues: 
         fromRange: d1
         toRange: d3
   - !at.ac.tuwien.dsg.depictool.entity.ControlAction
      actionID: LSR
      listOfParameters: 
      - !at.ac.tuwien.dsg.depictool.entity.Parameter
         paraName: expectedDataCompleteness
         type: double
         value: 100
      triggerValues: 
         fromRange: d2
         toRange: d3
   metricName: DataCompleteness
   monitorAction: 
      monitorActionID: dataCompletenessMeasurement
- !at.ac.tuwien.dsg.depictool.entity.MetricElasticityProcess
   listOfControlActions: 
   - !at.ac.tuwien.dsg.depictool.entity.ControlAction
      actionID: AddCtrl
      listOfParameters: 
      - !at.ac.tuwien.dsg.depictool.entity.Parameter
         paraName: numberOfVMs
         type: integer
         value: 1
      triggerValues: 
         fromRange: t1
         toRange: t2
   - !at.ac.tuwien.dsg.depictool.entity.ControlAction
      actionID: AddCtrl
      listOfParameters: 
      - !at.ac.tuwien.dsg.depictool.entity.Parameter
         paraName: numberOfVMs
         type: integer
         value: 1
      triggerValues: 
         fromRange: t2
         toRange: t3
   - !at.ac.tuwien.dsg.depictool.entity.ControlAction
      actionID: RmCtrl
      listOfParameters: 
      - !at.ac.tuwien.dsg.depictool.entity.Parameter
         paraName: numberOfVMs
         type: integer
         value: 1
      triggerValues: 
         fromRange: t3
         toRange: t2
   metricName: Throughput
   monitorAction: 
      monitorActionID: throughputMeasurement
